Loading python/3.7.3
  Loading requirement: tcl/8.6.8 gcc/8.3.0
usage: swa.py [-h] [--checkpoint CHECKPOINT]
              [--training-cycles TRAINING_CYCLES] [--cycle-steps CYCLE_STEPS]
swa.py: error: unrecognized arguments: --random-seed 193012823
Loading python/3.7.3
  Loading requirement: tcl/8.6.8 gcc/8.3.0
Traceback (most recent call last):
  File "swa.py", line 52, in <module>
    model = KWS_LSTM(input_dim = args.n_mfcc, hidden_dim = args.hidden, output_dim = len(args.word_list), batch_size = args.batch_size, device = device, quant_factor = 1, quant_beta = 1, wb = args.quant_w, abMVM = args.quant_actMVM, abNM = args.quant_actNM, ib = args.quant_inp, noise_level = args.noise_injectionT, blocks = 1, pool_method = 'Max', fc_blocks = 0, cy_div = 1, cy_scale = 1).to(device)
TypeError: __init__() missing 1 required positional argument: 'train_a'
